name: mekdev
favicon: null
layout_spectrum: 0.50778
typography_spectrum: 0.50119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2e3838'
    - '#7b7d71'
    - '#b4ae8f'
    - '#d8d767'
  brandStrength: 0.5
  lightness: 0.17903944407589734
  saturation: 0.6841110403183848
  rhythmicContrast: 0.5596997134853154
purpose: []
